apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: trigger # Kustomize here
  namespace: tektonci
spec:
  bindings:
    - ref: trigger-binding
  template:
    ref: trigger-template
  interceptors:
    # inject Parameter
    - ref:
        name: cel
        kind: ClusterInterceptor
      params:
        - name: "overlays"
          value:
            - key: "MODULE_PATH"
              expression: "string('backend/dummy')" # Kustomize here
            - key: "MANIFEST_FILE"
              expression: "string('base/deployment.yaml')"  # Kustomize here
            - key: "SOURCE_REPO_REVISION"
              expression: "string('main')"  # Kustomize here

    - ref:
        name: cel
        kind: ClusterInterceptor
      params:
        # filter changed files
        - name: "filter"
          value: |-
            (
              body.ref.split('/')[2] == 'main' ||
              body.base_ref.split('/')[2] == 'main' 
            )
            &&
            (
              body.commits.exists(
                commit,
                commit.added.exists(e, e.startsWith(extensions.MODULE_PATH)) ||
                commit.modified.exists(e, e.startsWith(extensions.MODULE_PATH)) ||
                commit.removed.exists(e, e.startsWith(extensions.MODULE_PATH))
              ) 
              || 
              body.head_commit.added.exists(e, e.startsWith(extensions.MODULE_PATH)) ||
              body.head_commit.modified.exists(e, e.startsWith(extensions.MODULE_PATH)) ||
              body.head_commit.removed.exists(e, e.startsWith(extensions.MODULE_PATH))
            )


        # pass to TriggerBinding
        - name: "overlays"
          value:
            - key: source-repo-revision
              # expression: "body.ref.split('/')[2]"
              expression: 'extensions.SOURCE_REPO_REVISION'
            - key: head-commit-url
              expression: "body.head_commit.url"
            - key: committer-name
              expression: "body.head_commit.committer.name"
            - key: committer-email
              expression: "body.head_commit.committer.email"
            - key: module-path
              expression: 'extensions.MODULE_PATH'
            - key: manifest-file
              expression: 'extensions.MANIFEST_FILE'
