apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elastic
generatorOptions:
    disableNameSuffixHash: true
configMapGenerator:
  - name: nginx-conf
    behavior: create
    files:
      - nginx.conf=nginx.conf
      - .htpasswd=.htpasswd