apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis-ha
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: redis-haproxy-config
    behavior: create
    files:
      - haproxy.cfg=haproxy.conf