apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: redis-ha
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: '17.13.2'
    helm:
      parameters:
        - name: image.debug
          value: 'true'
        # common
        - name: auth.enabled
          value: 'false'
        - name: auth.sentinel
          value: 'false'
        # image
        - name: image.debug
          value: 'true'
        # replication
        - name: master.count
          value: '1'
        - name: replica.replicaCount
          value: '3'
        # sentinel
        - name: sentinel.enabled
          value: 'true'
        - name: sentinel.quorum
          value: '2'
  syncPolicy:
    automated:
      prune: false
      selfHeal: false