apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  # k8s imagePullSecrets
  - name: image-pull-credentials
    files:
      - .dockerconfigjson=config.json
    type: kubernetes.io/dockerconfigjson