apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: prometheus-community-helm-repo
  namespace: argocd
stringData:
  name: prometheus-community-helm
  type: helm
  url: https://prometheus-community.github.io/helm-charts
  project: default
