apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elastic
  name: elasticsearch-conf
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |-
    cluster.name: myproj 	# 클러스터 이름
    discovery.type: single-node
      #    xpack.security.enabled: true
      #    xpack.security.transport.ssl.enabled: true
    network.host: 0.0.0.0			# 외부 접근

