apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
  - https://storage.googleapis.com/tekton-releases/triggers/previous/v0.23.0/release.yaml
  - https://storage.googleapis.com/tekton-releases/triggers/previous/v0.23.0/interceptors.yaml
  - https://storage.googleapis.com/tekton-releases/dashboard/latest/release.yaml
