apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:2-cha/gitops-config.git
    targetRevision: main
    path: manifests/elastic
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true