apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  # argocd repository connection
  - name: argocd-git-credentials
    namespace: argocd
    literals:
      - type=git
      - name=gitops-repo
      - url=git@github.com:2-cha/gitops-config.git
      - insecure=true
    files:
      - sshPrivateKey=id_rsa_gitops
patches:
  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: argocd-git-credentials
        namespace: argocd
        labels:
          argocd.argoproj.io/secret-type: repository
    target:
      name: argocd-git-credentials

