apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-robot
  namespace: tektonci


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triggers-example-eventlistener-binding
  namespace: tektonci
subjects:
  - kind: ServiceAccount
    name: tekton-robot
    namespace: tektonci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-example-eventlistener-clusterbinding
  namespace: tektonci
subjects:
  - kind: ServiceAccount
    name: tekton-robot
    namespace: tektonci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
