apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tektonci
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:2-cha/gitops-config.git
    targetRevision: main
    path: manifests/tektonci
  destination:
    server: https://kubernetes.default.svc
    namespace: tektonci
  syncPolicy:
    automated:
      prune: true
      selfHeal: true