apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
spec:
  # ReplicaSet 정의
  replicas: 3
  selector:
    matchLabels:
      app: demo-service
      tier: backend
  # Pods 정의
  template:
    metadata:
      name: demo-service
      labels:
        app: demo-service
        tier: backend
    spec:
      containers:
        - name: spring-boot
          image: m1nq/my-first-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: image-pull-credentials
