apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
  annotations:
    revision: main-cccecfcf5fec243d599e5cf3e41589fd787dbbf4
spec:
  # ReplicaSet 정의
  selector:
    matchLabels:
      app: demo-service
      tier: backend
  # Pods 정의
  template:
    metadata:
      name: demo-service
      labels:
        app: demo-service
        tier: backend
    spec:
      serviceAccount: ssm-read-s3-full
      volumes:
        - name: logback-conf-volume
          configMap:
            name: logback-conf
      containers:
        - name: spring-boot
          image: m1nq/my-first-app:main-cccecfcf5fec243d599e5cf3e41589fd787dbbf4
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
              name: api
            - containerPort: 9876
              protocol: TCP
              name: ops
          volumeMounts:
            - mountPath: /logback/config
              name: logback-conf-volume
          envFrom:
            - configMapRef:
                name: hibernate-search-conf
          readinessProbe:
            periodSeconds: 15
            timeoutSeconds: 2
            successThreshold: 2
            failureThreshold: 2
            httpGet:
              path: /
              port: 8080
      imagePullSecrets:
        - name: image-pull-credentials
