apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
  annotations:
    revision: main-3a5d2754bd1a1fc160e7af6d91fdd5633bf98ec3
spec:
  # ReplicaSet 정의
  replicas: 2
  selector:
    matchLabels:
      app: demo-service
      tier: backend
  # Pods 정의
  template:
    metadata:
      name: demo-service
      labels:
        app: demo-service
        tier: backend
    spec:
      serviceAccount: ssm-read-s3-full
      containers:
        - name: spring-boot
          image: m1nq/my-first-app:main-3a5d2754bd1a1fc160e7af6d91fdd5633bf98ec3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: image-pull-credentials
