apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
  annotations:
    revision: main-7e347cd8ca32f0f1a563b16d711b9991f5bc2d70
spec:
  # ReplicaSet 정의
  selector:
    matchLabels:
      app: demo-service
      tier: backend
  # Pods 정의
  template:
    metadata:
      name: demo-service
      labels:
        app: demo-service
        tier: backend
    spec:
      serviceAccount: ssm-read-s3-full
      volumes:
        - name: logback-conf-volume
          configMap:
            name: logback-conf
      containers:
        - name: spring-boot
          image: m1nq/my-first-app:main-7e347cd8ca32f0f1a563b16d711b9991f5bc2d70
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
              name: api
            - containerPort: 9876
              protocol: TCP
              name: ops
          volumeMounts:
            - mountPath: /logback/config
              name: logback-conf-volume
          envFrom:
            - configMapRef:
                name: hibernate-search-conf
            - configMapRef:
                name: logstash-url
          readinessProbe:
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 2
            failureThreshold: 2
            httpGet:
              path: /
              port: 8080
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 200m
              memory: 1Gi
      imagePullSecrets:
        - name: image-pull-credentials
