apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
  annotations:
    revision: main-818ba0656fb620a30818a72393240930763c5418
spec:
  # ReplicaSet 정의
  replicas: 3
  selector:
    matchLabels:
      app: demo-service
      tier: backend
  # Pods 정의
  template:
    metadata:
      name: demo-service
      labels:
        app: demo-service
        tier: backend
    spec:
      serviceAccount: ssm-readonly
      containers:
        - name: spring-boot
          image: m1nq/my-first-app:main-818ba0656fb620a30818a72393240930763c5418
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: image-pull-credentials
