apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
  annotations:
    revision: main-02b28766b776ba28aafcb0461ee15df299707d7a
spec:
  # ReplicaSet 정의
  replicas: 1
  selector:
    matchLabels:
      app: demo-service
      tier: backend
  # Pods 정의
  template:
    metadata:
      name: demo-service
      labels:
        app: demo-service
        tier: backend
    spec:
      serviceAccount: ssm-readonly
      containers:
        - name: spring-boot
          image: m1nq/my-first-app:main-02b28766b776ba28aafcb0461ee15df299707d7a
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: image-pull-credentials
