apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
  annotations:
    revision: main-8dfa908cfdb0727aeccd5b124559b58427c3d51d
spec:
  # ReplicaSet 정의
  replicas: 3
  selector:
    matchLabels:
      app: demo-service
      tier: backend
  # Pods 정의
  template:
    metadata:
      name: demo-service
      labels:
        app: demo-service
        tier: backend
    spec:
      serviceAccount: ssm-readonly
      containers:
        - name: spring-boot
          image: m1nq/my-first-app:main-8dfa908cfdb0727aeccd5b124559b58427c3d51d
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: image-pull-credentials
