apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
  annotations:
    revision: main-2f87474bb9eb1780f0743920f0b0cef836019cbe
spec:
  # ReplicaSet 정의
  replicas: 3
  selector:
    matchLabels:
      app: demo-service
      tier: backend
  # Pods 정의
  template:
    metadata:
      name: demo-service
      labels:
        app: demo-service
        tier: backend
    spec:
      serviceAccount: ssm-readonly
      containers:
        - name: spring-boot
          image: m1nq/my-first-app:main-2f87474bb9eb1780f0743920f0b0cef836019cbe
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: image-pull-credentials
