apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
  annotations:
    revision: main-11e2d1bc9882aec3f99580ed7510098f686c7c8f
spec:
  # ReplicaSet 정의
  replicas: 2
  selector:
    matchLabels:
      app: demo-service
      tier: backend
  # Pods 정의
  template:
    metadata:
      name: demo-service
      labels:
        app: demo-service
        tier: backend
    spec:
      serviceAccount: ssm-read-s3-full
      volumes:
        - name: logback-conf-volume
          configMap:
            name: logback-conf
      containers:
        - name: spring-boot
          image: m1nq/my-first-app:main-11e2d1bc9882aec3f99580ed7510098f686c7c8f
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /logback/config
              name: logback-conf-volume
      imagePullSecrets:
        - name: image-pull-credentials
