apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
  annotations:
    revision: main-d8d7172f87856ba27d1e41b87d8075f7e1dc7510
spec:
  # ReplicaSet 정의
  replicas: 2
  selector:
    matchLabels:
      app: demo-service
      tier: backend
  # Pods 정의
  template:
    metadata:
      name: demo-service
      labels:
        app: demo-service
        tier: backend
    spec:
      serviceAccount: ssm-read-s3-full
      volumes:
        - name: logback-conf-volume
          configMap:
            name: logback-conf
      containers:
        - name: spring-boot
          image: m1nq/my-first-app:main-d8d7172f87856ba27d1e41b87d8075f7e1dc7510
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /logback/config
              name: logback-conf-volume
          readinessProbe:
            periodSeconds: 15
            timeoutSeconds: 2
            successThreshold: 2
            failureThreshold: 2
            httpGet:
              path: /
              port: 8080
      imagePullSecrets:
        - name: image-pull-credentials
