apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
  annotations:
    revision: main-01ad89df17db6281a8584ac766eadf763b5adae2
spec:
  # ReplicaSet 정의
  replicas: 2
  selector:
    matchLabels:
      app: demo-service
      tier: backend
  # Pods 정의
  template:
    metadata:
      name: demo-service
      labels:
        app: demo-service
        tier: backend
    spec:
      serviceAccount: ssm-readonly
      containers:
        - name: spring-boot
          image: m1nq/my-first-app:main-01ad89df17db6281a8584ac766eadf763b5adae2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: image-pull-credentials
