apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-service 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-service 
  minReplicas: 2
  maxReplicas: 7
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
# targetCPUUtilizationPercentage: 50
  metrics:
    - type: Pods
      pods:
        metric:
          name: http_server_requests_per_second
        target:
          type: AverageValue
          averageValue: "3"