apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: demo-service
    tier: backend
  ports:
    - port: 80
      name: api
      targetPort: api
    - port: 9876
      name: ops
      targetPort: ops
  externalTrafficPolicy: Local
  type: NodePort
