apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: webhook-listener
  namespace: tektonci
spec:
  serviceAccountName: tekton-robot
  resources:
    kubernetesResource:
      serviceType: NodePort
      servicePort: 8080
  triggers:
    - triggerRef: trigger
      # Add new triggers with:
      # kubectl patch el webhook-listener -n tektonci --type "json" --patch-file listener-patch.json