apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elastic
resources:
  - namespace
  - elasticsearch
  - logstash
  - kibana
# enable nginx only if you want to expose kibana to the internet, with basic auth
#  - nginx